// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJzOt5puSPJoMQ0RSYWmZ5xG8_E8dyNgE',
    appId: '1:283628213208:web:52b7e5cb4e497790cc58ad',
    messagingSenderId: '283628213208',
    projectId: 'water-tank-insights',
    authDomain: 'water-tank-insights.firebaseapp.com',
    storageBucket: 'water-tank-insights.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxdKnbfHb19wna46Y2hfPF9iAh-LahSdY',
    appId: '1:283628213208:android:71ff20a18ca93f67cc58ad',
    messagingSenderId: '283628213208',
    projectId: 'water-tank-insights',
    storageBucket: 'water-tank-insights.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSmFWY3itaH-wQWDRBWwgNyJRnNYlUrs8',
    appId: '1:283628213208:ios:1e88c52516d8678fcc58ad',
    messagingSenderId: '283628213208',
    projectId: 'water-tank-insights',
    storageBucket: 'water-tank-insights.firebasestorage.app',
    iosBundleId: 'com.o2tech.waterTankInsights',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSmFWY3itaH-wQWDRBWwgNyJRnNYlUrs8',
    appId: '1:283628213208:ios:1e88c52516d8678fcc58ad',
    messagingSenderId: '283628213208',
    projectId: 'water-tank-insights',
    storageBucket: 'water-tank-insights.firebasestorage.app',
    iosBundleId: 'com.o2tech.waterTankInsights',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJzOt5puSPJoMQ0RSYWmZ5xG8_E8dyNgE',
    appId: '1:283628213208:web:302a726980b32f08cc58ad',
    messagingSenderId: '283628213208',
    projectId: 'water-tank-insights',
    authDomain: 'water-tank-insights.firebaseapp.com',
    storageBucket: 'water-tank-insights.firebasestorage.app',
  );
}
